import { describe, expect, it } from 'vitest';
import { countDemonstratedFixes, mapCorrections, parseAnalysis, remarkFor, splitSentences } from './analysis';
import type { Correction, EnglishAnalysisResult } from '../types';
const correction = (overrides: Partial<Correction> = {}): Correction => ({ id: 'c1', sentenceId: 'sentence_1', originalText: 'go', occurrence: 1, replacementText: 'went', simpleExplanation: 'You are talking about yesterday, so use went.', category: 'grammar', severity: 'important', correctionType: 'error', ...overrides });
const feedback = (overrides: Partial<EnglishAnalysisResult> = {}): EnglishAnalysisResult => ({ originalTranscript: 'Yesterday I go to the market.', correctedTranscript: 'Yesterday I went to the market.', corrections: [correction()], scores: { grammar: 7, vocabulary: 7.5, clarity: 8, overall: 7.5 }, remark: 'Very Good', teacherFeedback: 'Your story was easy to follow. Practice words for the past.', strengths: ['You gave a clear place and time.'], focusNext: 'Use past-time words when speaking about yesterday.', ...overrides });
describe('teacher notebook exact alignment', () => {
  it('preserves every character when splitting sentences', () => { const text = 'First, a thought.\n  Another one! Is that clear?'; expect(splitSentences(text).map(s => s.text).join('')).toBe(text); });
  it('selects only the requested whole-word occurrence within its sentence', () => { const text = 'I go where you go. I go home.'; const { mapped } = mapCorrections(text, [correction({ occurrence: 2 })]); expect(mapped[0].start).toBe(15); expect(text.slice(mapped[0].start, mapped[0].end)).toBe('go'); });
  it('respects stable sentence IDs', () => { const text = 'I go outside. I go home.'; expect(mapCorrections(text, [correction({ sentenceId: 'sentence_2' })]).mapped[0].start).toBe(16); });
  it('does not match a word inside another word', () => { expect(mapCorrections('I forgot.', [correction()]).unmapped).toHaveLength(1); });
  it.each(["I can't swim, but I can run.", 'I can’t swim, but I can run.'])('skips contraction substrings: %s', text => { const mapped = mapCorrections(text, [correction({ originalText: 'can', replacementText: 'could' })]).mapped; expect(mapped[0].start).toBe(text.lastIndexOf('can')); });
  it('does not highlight uncertain sentence or occurrence references', () => { const result = mapCorrections('I go home.', [correction({ occurrence: 9 }), correction({ id: 'c2', sentenceId: 'sentence_99' })]); expect(result.mapped).toHaveLength(0); expect(result.unmapped).toHaveLength(2); });
  it('separates overlapping corrections', () => { const result = mapCorrections('I go home.', [correction(), correction({ id: 'c2', originalText: 'go home', replacementText: 'went home' })]); expect(result.mapped).toHaveLength(1); expect(result.unmapped).toHaveLength(1); });
});
describe('validated teacher response', () => {
  it('accepts correct JSON and derives the consistent score remark', () => { const data = feedback({ remark: 'Bad' }); expect(parseAnalysis(JSON.stringify(data), data.originalTranscript).remark).toBe('Very Good'); });
  it('accepts a JSON code fence without inventing output', () => { const data = feedback(); expect(parseAnalysis('```json\n' + JSON.stringify(data) + '\n```', data.originalTranscript).scores.overall).toBe(7.5); });
  it('rejects invalid JSON', () => { expect(() => parseAnalysis('Hello!', 'Hello!')).toThrow(); });
  it.each([-1, 10.1, NaN, Infinity])('rejects unusable scores: %s', score => { const data = feedback(); data.scores.overall = score; expect(() => parseAnalysis(JSON.stringify(data), data.originalTranscript)).toThrow(); });
  it('rejects a changed original transcript', () => { expect(() => parseAnalysis(JSON.stringify(feedback()), 'Yesterday I went to the market.')).toThrow(); });
  it('rejects extra fields and missing feedback', () => { const data = { ...feedback(), pronunciation: 10 }; expect(() => parseAnalysis(JSON.stringify(data), data.originalTranscript)).toThrow(); });
  it('rejects duplicate IDs', () => { const data = feedback({ corrections: [correction(), correction()] }); expect(() => parseAnalysis(JSON.stringify(data), data.originalTranscript)).toThrow(); });
  it('rejects an unrelated or blank corrected version', () => { for (const correctedTranscript of ['   ', 'The world is beautiful.']) { const data = feedback({ correctedTranscript }); expect(() => parseAnalysis(JSON.stringify(data), data.originalTranscript)).toThrow(); } });
  it('leaves already-correct English unchanged', () => { const originalTranscript = 'I went to the market yesterday and bought some vegetables.'; const data = feedback({ originalTranscript, correctedTranscript: originalTranscript, corrections: [] }); expect(parseAnalysis(JSON.stringify(data), originalTranscript).corrections).toEqual([]); });
  it('represents did → made with a simple explanation', () => { const data = feedback({ originalTranscript: 'I did a mistake.', correctedTranscript: 'I made a mistake.', corrections: [correction({ originalText: 'did', replacementText: 'made', simpleExplanation: 'We normally say “make a mistake”.' })] }); expect(parseAnalysis(JSON.stringify(data), data.originalTranscript).correctedTranscript).toBe('I made a mistake.'); });
  it('keeps a natural improvement distinct from an error', () => { const data = feedback({ originalTranscript: 'I have one doubt.', correctedTranscript: 'I have a question.', corrections: [correction({ originalText: 'one doubt', replacementText: 'a question', correctionType: 'natural_improvement', severity: 'minor' })] }); expect(parseAnalysis(JSON.stringify(data), data.originalTranscript).corrections[0].correctionType).toBe('natural_improvement'); });
  it('retains uncertain corrections separately without silently rewriting', () => { const data = feedback({ corrections: [correction({ originalText: 'nonexistent' })] }); expect(parseAnalysis(JSON.stringify(data), data.originalTranscript).correctedTranscript).toBe(data.originalTranscript); });
  it('accepts harmless spacing cleanup when an extra word is removed', () => { const data = feedback({ originalTranscript: 'I went to to the market.', correctedTranscript: 'I went to the market.', corrections: [correction({ originalText: 'to', occurrence: 2, replacementText: '' })] }); expect(parseAnalysis(JSON.stringify(data), data.originalTranscript).correctedTranscript).toBe('I went to the market.'); });
  it.each([[0,'Very Bad'],[2.9,'Very Bad'],[3,'Bad'],[4.9,'Bad'],[5,'Good'],[6.9,'Good'],[7,'Very Good'],[8.4,'Very Good'],[8.5,'Excellent'],[10,'Excellent']])('maps score %s to %s', (score, remark) => { expect(remarkFor(Number(score))).toBe(remark); });
});
describe('honest attempt comparison', () => {
  it('does not call omitted mistakes fixed', () => { expect(countDemonstratedFixes(feedback(), feedback({ originalTranscript: 'I like fruit.', corrections: [] }))).toBe(0); });
  it('counts demonstrated replacement once', () => { expect(countDemonstratedFixes(feedback(), feedback({ originalTranscript: 'I went to the market.', corrections: [] }))).toBe(1); });
  it('does not count two old mistakes against one replacement occurrence', () => { expect(countDemonstratedFixes(feedback({ corrections: [correction(), correction({ id: 'c2', occurrence: 2 })] }), feedback({ originalTranscript: 'I went home.', corrections: [] }))).toBe(1); });
  it('counts an inserted article', () => { expect(countDemonstratedFixes(feedback({ corrections: [correction({ originalText: 'market', replacementText: 'the market' })] }), feedback({ originalTranscript: 'I went to the market.', corrections: [] }))).toBe(1); });
  it('does not count optional style as a fixed error', () => { expect(countDemonstratedFixes(feedback({ corrections: [correction({ correctionType: 'natural_improvement' })] }), feedback({ originalTranscript: 'I went home.', corrections: [] }))).toBe(0); });
});
