import { useEffect, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowLeft, ArrowRight, BookOpen, ChevronLeft, ChevronRight, RotateCcw } from 'lucide-react';
import { getHistory, getSession } from '../services/practiceService';
import { readableDate, formatDuration } from '../lib/dates';
import { AttemptComparison, ScoreCards, TeacherNotebook, TeacherSummary } from '../components/Feedback';
export default function HistoryPage() {
  const { pathname } = useLocation(); const id = pathname.split('/')[2]; const [page, setPage] = useState(0); const [selected, setSelected] = useState(0); const [reload, setReload] = useState(0);
  const [list, setList] = useState<Awaited<ReturnType<typeof getHistory>> | null>(null); const [detail, setDetail] = useState<Awaited<ReturnType<typeof getSession>> | null>(null); const [error, setError] = useState('');
  useEffect(() => { let live = true; setError(''); setDetail(null); setList(null); setSelected(0); if (id) void getSession(id).then(data => { if (live) { setDetail(data); setSelected(data.attempts.length - 1); } }).catch(e => { if (live) setError(e.message); }); else void getHistory(page).then(data => { if (live) setList(data); }).catch(e => { if (live) setError(e.message); }); return () => { live = false; }; }, [id, page, reload]);
  if (error) return <div className="empty-state"><h2>This chapter needs a moment.</h2><p>{error}</p><button className="button button-primary" onClick={() => setReload(n => n + 1)}>Try again</button><Link className="text-button" to="/history">Back to history</Link></div>;
  if (id) {
    if (!detail) return <div className="loading-page" role="status"><p>Opening your practice notebook…</p></div>;
    const attempt = detail.attempts[selected];
    return <><Link to="/history" className="back-link"><ArrowLeft size={16} /> All practice history</Link><div className="page-heading"><div><span className="kicker">YOUR PRACTICE NOTEBOOK</span><h1 style={{ fontSize: '1.8rem' }}>{detail.session.topic}</h1><p><span className="capitalize">{detail.session.difficulty}</span> · {detail.session.topic_category} · {readableDate(detail.session.created_at)}</p></div></div><div className="attempt-tabs" aria-label="Choose an attempt">{detail.attempts.map((a, index) => <button key={a.id} className={selected === index ? 'active' : ''} onClick={() => setSelected(index)} aria-pressed={selected === index}>Attempt {a.attempt_number} · {a.analysis.scores.overall.toFixed(1)}</button>)}</div>{attempt && <><p className="muted">{formatDuration(attempt.duration_seconds)} spoken · {readableDate(attempt.completed_at)}</p><ScoreCards scores={attempt.analysis.scores} remark={attempt.analysis.remark} />{selected > 0 && <AttemptComparison previous={detail.attempts[selected - 1].analysis} current={attempt.analysis} />}<TeacherNotebook key={attempt.id} analysis={attempt.analysis} /><TeacherSummary analysis={attempt.analysis} /></>}<div className="results-actions"><Link className="button button-primary" to={`/practice?session=${detail.session.id}`}><RotateCcw size={17} /> Try this topic again</Link><Link className="button button-outline" to="/practice">New topic <ArrowRight size={17} /></Link></div></>;
  }
  return <><div className="page-heading"><div><span className="kicker">EVERY CONVERSATION IS A CHAPTER</span><h1>Your practice story.</h1><p>Revisit a topic, remember a lesson, and hear how far you’ve come.</p></div></div>{!list ? <div className="loading-page" role="status"><p>Opening your practice history…</p></div> : list.sessions.length === 0 ? <div className="empty-state"><img src="/assets/learning-scene.png" alt="" width="1254" height="1254" /><h2>{page ? 'That’s your story so far.' : 'A fresh notebook. All yours.'}</h2><p>{page ? 'Go back to revisit an earlier practice.' : 'Your topics and teacher feedback will appear here after your first successful analysis.'}</p>{page ? <button className="button button-primary" onClick={() => setPage(page - 1)}>Previous page</button> : <Link className="button button-primary" to="/practice">Let’s start speaking <ArrowRight size={17} /></Link>}</div> : <><div className="history-list">{list.sessions.map(session => { const attempts = [...session.practice_attempts].sort((a, b) => a.attempt_number - b.attempt_number); const latest = attempts.at(-1); const delta = attempts.length > 1 ? latest!.overall_score - attempts[0].overall_score : null; return <Link className="history-row" key={session.id} to={`/history/${session.id}`}><div className="section-icon"><BookOpen size={22} /></div><div className="history-row-main"><h3>{session.topic}</h3><div className="history-row-meta"><span className="pill capitalize">{session.difficulty}</span><span>{readableDate(session.completed_at || session.created_at)}</span><span>·</span><span>{attempts.length} {attempts.length === 1 ? 'attempt' : 'attempts'}</span>{delta !== null && <span>{delta > 0 ? '+' : ''}{delta.toFixed(1)} points</span>}</div></div><div className="history-row-score"><strong>{latest?.overall_score.toFixed(1) ?? '—'}</strong><small>Latest / 10</small></div><ChevronRight size={20} /></Link>; })}</div><div className="pagination"><button className="button button-outline" disabled={page === 0} onClick={() => setPage(page - 1)}><ChevronLeft size={16} /> Previous</button><span>Page {page + 1}</span><button className="button button-outline" disabled={!list.hasMore} onClick={() => setPage(page + 1)}>Next <ChevronRight size={16} /></button></div></>}</>;
}
