import { useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowDown, ArrowRight, AudioLines, BookOpen, Check, ChevronDown, CirclePlay, Flame, Headphones, LockKeyhole, Menu, Mic, PencilLine, ShieldCheck, Sparkles, TrendingUp, X } from 'lucide-react';
import { SpikooLogo, ThemeToggle } from '../components/Brand';
import { TeacherNotebook } from '../components/Feedback';
import { useAuth } from '../context/AuthContext';
import type { EnglishAnalysisResult } from '../types';
const sample: EnglishAnalysisResult = { originalTranscript: 'Yesterday I go to the market.\nI bought some fresh vegetables.', correctedTranscript: 'Yesterday I went to the market.\nI bought some fresh vegetables.', corrections: [{ id: 'example-1', sentenceId: 'sentence_1', originalText: 'go', occurrence: 1, replacementText: 'went', simpleExplanation: 'You’re talking about yesterday, so the action already happened. Use “went” instead of “go”.', category: 'grammar', severity: 'important', correctionType: 'error' }], scores: { grammar: 0, vocabulary: 0, clarity: 0, overall: 0 }, remark: 'Good', teacherFeedback: '', strengths: [], focusNext: '' };
const faqs = [
  ['How does Spikoo help me speak better English?', 'Choose a topic, record yourself, and listen back. Then get AI teacher feedback that shows what to change and explains why in simple English. Try the same topic again to put what you learned into practice.'],
  ['Do I need to be good at English already?', 'No. Choose Beginner, Intermediate, or Advanced during setup. Your topics and feedback are matched to your level, and you can change your level whenever you like.'],
  ['Is Spikoo free to use?', 'Spikoo has no subscription or paid plan. AI transcription and feedback use your own Puter account and its available allowance. If that allowance runs out, check your Puter account before trying again; Spikoo does not cover additional AI usage.'],
  ['Why do I connect a Puter account?', 'Your Spikoo account keeps your learning history. Puter gives you access to speech-to-text and AI feedback without an AI API key. You only need to connect Puter when you want AI feedback.'],
  ['What happens to my recording?', 'Your recording stays in this browser until you choose Analyze. Then it is sent to Puter for transcription. Spikoo discards its local audio after successful feedback and saves only text, corrections, and progress. Puter’s own processing and retention policies apply to audio you send.'],
  ['Can I practice on my phone?', 'Yes. Spikoo works on modern mobile browsers that support microphone recording. Use a secure connection, allow microphone access, and keep the page open while speaking.'],
];
export default function Landing() {
  const { user } = useAuth(); const [menu, setMenu] = useState(false);
  const art = useRef<HTMLDivElement>(null);
  const start = user ? '/practice' : '/signup';
  function parallax(event: React.PointerEvent<HTMLElement>) {
    if (event.pointerType !== 'mouse' || matchMedia('(max-width: 800px), (hover: none)').matches || matchMedia('(prefers-reduced-motion: reduce)').matches || !art.current) return;
    const rect = event.currentTarget.getBoundingClientRect();
    art.current.style.setProperty('--move-x', `${((event.clientX - rect.left) / rect.width - .5) * 12}px`);
    art.current.style.setProperty('--move-y', `${((event.clientY - rect.top) / rect.height - .5) * 10}px`);
  }
  const reset = () => { art.current?.style.setProperty('--move-x', '0px'); art.current?.style.setProperty('--move-y', '0px'); };
  return <><header className="landing-header"><div className="nav-shell"><SpikooLogo /><nav className={menu ? 'landing-nav open' : 'landing-nav'} aria-label="Main navigation"><a href="#how-it-works" onClick={() => setMenu(false)}>How it works</a><a href="#features" onClick={() => setMenu(false)}>Features</a><a href="#progress" onClick={() => setMenu(false)}>Progress</a><a href="#faq" onClick={() => setMenu(false)}>FAQ</a></nav><div className="nav-actions"><ThemeToggle /><Link to={user ? '/practice' : '/signin'} className="button button-outline nav-signin">{user ? 'My practice' : 'Sign in'}</Link><Link to={start} className="button button-primary nav-cta">Start speaking <ArrowRight size={16} /></Link><button className="icon-button mobile-menu" onClick={() => setMenu(!menu)} aria-expanded={menu} aria-label="Toggle navigation">{menu ? <X /> : <Menu />}</button></div></div></header>
    <main id="main-content"><section className="hero" onPointerMove={parallax} onPointerLeave={reset}><div className="hero-inner"><div className="hero-copy"><div className="eyebrow"><Sparkles size={16} fill="currentColor" /> Your AI English Speaking Partner</div><h1>Speak English<br />with <span className="gradient-text">confidence.</span></h1><p className="hero-description">Practice real conversations, understand your mistakes,<br className="desktop-break" /> and improve every time you speak with Spikoo.</p><div className="hero-principles"><div><span className="principle-icon"><Mic /></span><p><strong>Speak</strong><small>Find your voice</small></p></div><div><span className="principle-icon"><BookOpen /></span><p><strong>Learn</strong><small>Understand why</small></p></div><div><span className="principle-icon"><TrendingUp /></span><p><strong>Grow</strong><small>See your progress</small></p></div></div><div className="hero-cta"><Link to={start} className="button button-primary button-large">Start speaking <ArrowRight size={21} /></Link><a href="#how-it-works" className="watch-link"><CirclePlay size={22} /> See how it works</a></div><div className="hero-reassurance"><LockKeyhole size={14} /> No Spikoo subscription <span>•</span> Learn at your own pace</div></div><div className="hero-art" ref={art}><div className="hero-orbit" /><img className="learning-scene" src="/assets/learning-scene.png" alt="A learner in blue headphones practicing English at a microphone, with a notebook and a cheerful Hello speech bubble" fetchPriority="high" width="1254" height="1254" /><div className="floating-note"><span className="note-check"><Check size={20} /></span><div><strong>Small steps. Real progress.</strong><small>A little more confident, every day.</small></div></div><div className="hero-handwritten">Your next chapter<br />starts with a conversation. <span>↗</span></div></div></div><a href="#how-it-works" className="scroll-cue">A little practice goes a long way <ArrowDown size={16} /></a></section>
    <section className="promise-strip" aria-label="Made for your learning"><div><Headphones /><span>A space to speak freely</span></div><div><PencilLine /><span>Feedback you understand</span></div><div><Flame /><span>A habit worth building</span></div><div><ShieldCheck /><span>Your learning, kept private</span></div></section>
    <section className="section how-section" id="how-it-works"><div className="section-heading"><span className="kicker">SPEAK. LEARN. GROW.</span><h2>Big confidence starts<br />with a small conversation.</h2><p>No pressure. No complicated lessons. Just you, a topic, and a little practice.</p></div><div className="steps-grid">{[{ icon: Mic, name: 'Make it your story', text: 'Get a topic that fits your level. Take a breath, then speak naturally.', tag: '01 · SPEAK' }, { icon: PencilLine, name: 'Meet your next “aha!”', text: 'Listen back, see the corrections, and understand the why behind each one.', tag: '02 · LEARN' }, { icon: TrendingUp, name: 'Hear the difference', text: 'Try the same topic again. Track your progress, one conversation at a time.', tag: '03 · GROW' }].map(({ icon: Icon, name, text, tag }) => <article className="step-card" key={name}><div className="step-icon"><Icon size={31} /></div><span className="step-number">{tag}</span><h3>{name}</h3><p>{text}</p></article>)}</div></section>
    <section className="feedback-section" id="features"><div className="section feedback-inner"><div className="feedback-copy"><span className="kicker">FEEDBACK THAT CLICKS</span><h2>More than a correction.<br /><span className="gradient-text">A little understanding.</span></h2><p>Remember the teacher who made things make sense? That’s the feeling.</p><ul className="check-list"><li><Check /> See exactly what to change</li><li><Check /> Understand why, in simple English</li><li><Check /> Keep your own meaning and voice</li></ul><Link className="text-link" to={start}>Meet your English practice partner <ArrowRight size={18} /></Link></div><div className="sample-notebook"><span className="example-label">AN EXAMPLE OF TEACHER FEEDBACK</span><TeacherNotebook analysis={sample} compact /></div></div></section>
    <section className="section progress-story" id="progress"><div className="habit-card"><div className="habit-head"><span className="section-icon"><Flame size={27} /></span><div><h3>Show up for yourself.</h3><p>Every practice day is a small win.</p></div></div><div className="habit-illustration" aria-hidden="true">{Array.from({ length: 84 }, (_, i) => <span key={i} className={`habit-cell shade-${(i * 17 + i % 9) % 5}`} />)}</div><span className="illustration-label">Illustration · Your activity starts with your first practice</span><div className="habit-bottom"><AudioLines /><span>Your voice today.<br /><strong>A more confident you tomorrow.</strong></span></div></div><div className="progress-copy"><span className="kicker">PROGRESS YOU CAN SEE</span><h2>A little better.<br />A little braver.<br /><span className="gradient-text">Every time you speak.</span></h2><p>Build a streak, revisit your feedback, and see how your English develops. Your progress is made of real practice.</p><Link to={start} className="button button-outline">Start your first practice <ArrowRight size={18} /></Link></div></section>
    <section className="section faq-section" id="faq"><div className="section-heading"><span className="kicker">A FEW THINGS YOU MIGHT WONDER</span><h2>Let’s clear things up.</h2></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown size={20} /></summary><p>{answer}</p></details>)}</div></section><section className="closing-section"><div className="eyebrow"><Sparkles size={16} /> A little practice. A world of possibilities.</div><h2>Your voice deserves<br />to be heard.</h2><p>Take the first small step. We’ll help with the next one.</p><Link className="button button-primary button-large" to={start}>Let’s start speaking <ArrowRight size={20} /></Link></section></main>
    <footer className="footer"><SpikooLogo /><p>Your space to speak, learn, and grow.</p><div><Link to="/privacy">Privacy</Link><a href="#faq">Questions?</a><span>© {new Date().getFullYear()} Spikoo</span></div></footer></>;
}

