import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, ArrowRight, BookOpen, Mic, Sparkles, TrendingUp } from 'lucide-react';
import { SpikooLogo, ThemeToggle } from '../components/Brand';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';
import { updatePreferences, updateProfile } from '../services/authService';
import type { EnglishLevel } from '../types';
export const levelDescriptions = { beginner: 'I know a few words. I want to feel comfortable with everyday English.', intermediate: 'I can hold a conversation. I want to express myself more clearly.', advanced: 'I speak comfortably. I want to communicate complex ideas with confidence.' };
export default function Onboarding() {
  const { user, profile, reload } = useAuth(); const { theme } = useTheme(); const navigate = useNavigate();
  const [step, setStep] = useState(0); const [name, setName] = useState(profile?.display_name || ''); const [level, setLevel] = useState<EnglishLevel>(profile?.english_level ?? 'beginner'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function complete() { if (!user || busy) return; setBusy(true); setError(''); try { await updatePreferences(user.id, theme, Intl.DateTimeFormat().resolvedOptions().timeZone); await updateProfile(user.id, name, level); await reload(); navigate('/practice', { replace: true }); } catch (e) { setError(e instanceof Error ? e.message : 'Your preferences could not be saved.'); } finally { setBusy(false); } }
  return <><header className="simple-header"><SpikooLogo /><ThemeToggle /></header><main className="onboarding" id="main-content"><div className="onboarding-progress" aria-label={`Step ${step + 1} of 3`}>{[0, 1, 2].map(n => <span key={n} className={n <= step ? 'active' : ''} />)}</div>{step === 0 ? <><div className="eyebrow"><Sparkles size={16} /> SPEAK. LEARN. GROW.</div><h1>Welcome to your<br /><span className="gradient-text">next chapter.</span></h1><p>Big confidence begins with small conversations.<br />Let’s make this space yours.</p><img className="onboarding-art" src="/assets/learning-scene.png" width="1254" height="1254" alt="A welcoming space to practice English" /><label className="onboarding-name">What should we call you?<input value={name} onChange={e => setName(e.target.value)} maxLength={60} autoComplete="given-name" placeholder="Your name" /></label></> : step === 1 ? <><span className="kicker">LET’S FIND YOUR STARTING POINT</span><h1>Where are you<br /><span className="gradient-text">with English?</span></h1><p>There’s no right or wrong answer. You can change this whenever you like.</p><div className="level-options" role="group" aria-label="Your English level">{(['beginner', 'intermediate', 'advanced'] as const).map((value, index) => <button className={`level-option ${value === level ? 'selected' : ''}`} aria-pressed={value === level} onClick={() => setLevel(value)} key={value}><span className="level-bars" aria-hidden="true">{[0, 1, 2].map(n => <span key={n} className={n <= index ? 'filled' : ''} style={{ height: `${12 + n * 9}px` }} />)}</span><h3 className="capitalize">{value}</h3><p>{levelDescriptions[value]}</p></button>)}</div></> : <><div className="eyebrow"><Sparkles size={16} /> Small steps, at your own pace</div><h1>You speak.<br /><span className="gradient-text">We’ll help you grow.</span></h1><p>Speak about a topic. Spikoo will show your mistakes and explain how to improve them.</p><div className="onboarding-steps">{[{ icon: Mic, title: 'Speak, then listen', text: 'Record your thoughts and listen before you analyze.' }, { icon: BookOpen, title: 'Learn the why', text: 'Connect Puter for simple AI teacher feedback.' }, { icon: TrendingUp, title: 'Try it again', text: 'Practice the same topic and see what changes.' }].map(({ icon: Icon, title, text }) => <div className="onboarding-step" key={title}><div className="section-icon"><Icon size={24} /></div><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></>}{error && <div className="notice" role="alert">{error}</div>}<div className="onboarding-actions">{step > 0 && <button className="button button-outline" disabled={busy} onClick={() => setStep(step - 1)}><ArrowLeft size={16} /> Back</button>}<button className="button button-primary" disabled={busy || !name.trim()} onClick={() => step < 2 ? setStep(step + 1) : void complete()}>{busy ? 'Getting ready…' : step === 2 ? 'Start my first practice' : 'Continue'} <ArrowRight size={18} /></button></div></main></>;
}
