import { useState } from 'react';
import type { FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Check, LockKeyhole, LogOut, ShieldCheck } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';
import { updatePreferences, updateProfile } from '../services/authService';
import type { EnglishLevel, Theme } from '../types';
export default function ProfilePage() {
  const { user, profile, preferences, reload, signOut } = useAuth(); const { theme, setTheme } = useTheme(); const navigate = useNavigate();
  const [name, setName] = useState(profile!.display_name); const [level, setLevel] = useState<EnglishLevel>(profile!.english_level); const [choice, setChoice] = useState<Theme>(theme); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  async function save(event: FormEvent) { event.preventDefault(); if (busy) return; setBusy(true); setError(''); setNotice(''); try { await updateProfile(user!.id, name, level); await updatePreferences(user!.id, choice, Intl.DateTimeFormat().resolvedOptions().timeZone); setTheme(choice); await reload(); setNotice('Your preferences have been saved.'); } catch (e) { setError(e instanceof Error ? e.message : 'Your preferences could not be saved.'); } finally { setBusy(false); } }
  async function logout() { setBusy(true); setError(''); try { await signOut(); navigate('/'); } catch (e) { setError(e instanceof Error ? e.message : 'Sign out did not finish.'); } finally { setBusy(false); } }
  return <><div className="page-heading"><div><span className="kicker">MAKE THIS SPACE YOURS</span><h1>Your learning, your way.</h1><p>A few small settings to help you feel at home.</p></div></div><div className="profile-layout"><form className="profile-form" onSubmit={save}><section className="panel"><div className="profile-email"><div className="avatar">{name.slice(0, 1).toUpperCase() || 'S'}</div><div><strong>Your Spikoo account</strong><small>{user?.email}</small></div></div><label>Display name<input value={name} onChange={e => setName(e.target.value)} required minLength={1} maxLength={60} autoComplete="name" /></label><label>English level<select value={level} onChange={e => setLevel(e.target.value as EnglishLevel)}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label></section><section className="panel"><h2>Feel at home</h2><label>Appearance<select value={choice} onChange={e => setChoice(e.target.value as Theme)}><option value="light">Light — a bright place to practice</option><option value="dark">Dark — a calmer evening space</option><option value="system">Follow my device</option></select></label><p style={{ fontSize: '.78rem', margin: '20px 0 0' }}>Practice days follow your time zone: {preferences?.timezone.replaceAll('_', ' ')}. Saving updates this to your current device’s time zone.</p></section>{error && <div className="notice" role="alert">{error}</div>}{notice && <div className="notice success" role="status"><Check size={16} />{notice}</div>}<button disabled={busy || !name.trim()} className="button button-primary" type="submit">{busy ? 'Saving…' : 'Save my preferences'}<Check size={17} /></button></form><aside className="profile-info"><div className="panel"><h3><ShieldCheck size={21} className="blue" /> Your learning is personal</h3><p>Your practice history belongs to your Spikoo account. Other learners cannot read your transcripts or feedback.</p><p>Spikoo never permanently stores your voice recordings.</p><Link to="/privacy" className="text-link">About your privacy <ArrowIcon /></Link></div><div className="panel"><h3><LockKeyhole size={20} className="blue" /> A separate key to AI feedback</h3><p>Puter gives you access to transcription and AI teacher feedback using your own allowance. It is separate from your Spikoo sign-in.</p><p>Signing out of Spikoo does not sign you out of Puter.</p><button className="button button-outline" disabled={busy} onClick={() => void logout()}><LogOut size={17} /> Sign out of Spikoo</button></div></aside></div></>;
}
function ArrowIcon() { return <span aria-hidden="true">↗</span>; }
