import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Clock3, Flame, Mic, Trophy } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { getProgress } from '../services/progressService';
import { localDate } from '../lib/dates';
import { ActivityGrid, ProgressChart } from '../components/ProgressVisuals';
export default function Progress() {
  const { preferences } = useAuth(); const [data, setData] = useState<Awaited<ReturnType<typeof getProgress>> | null>(null); const [error, setError] = useState(''); const [reload, setReload] = useState(0);
  useEffect(() => { let live = true; setError(''); void getProgress(preferences!.timezone).then(value => { if (live) setData(value); }).catch(e => { if (live) setError(e.message); }); return () => { live = false; }; }, [preferences, reload]);
  if (error) return <div className="empty-state"><h2>Your progress needs a moment.</h2><p>{error}</p><button className="button button-primary" onClick={() => setReload(n => n + 1)}>Try again</button></div>;
  if (!data) return <div className="loading-page" role="status"><p>Gathering your small wins…</p></div>;
  const { stats, activity, trend } = data; const delta = trend.length > 1 ? trend.at(-1)!.overall_score - trend[0].overall_score : null;
  return <><div className="page-heading"><div><span className="kicker">ONE CONVERSATION AT A TIME</span><h1>Look how you’re growing.</h1><p>Your real practice. Your own pace. Every small step counts.</p></div><Link to="/practice" className="button button-primary">Keep speaking <ArrowRight size={16} /></Link></div>{stats.total_attempts === 0 ? <div className="empty-state"><img src="/assets/learning-scene.png" alt="" width="1254" height="1254" /><h2>Your next chapter starts with one conversation.</h2><p>Your first analyzed attempt will begin your activity, scores, and streak. Let’s take that first small step.</p><Link className="button button-primary" to="/practice">Start my first practice <ArrowRight size={17} /></Link></div> : <><div className="stats-grid">{[{ icon: Flame, value: stats.current_streak, unit: 'days', label: 'Current streak' }, { icon: Trophy, value: stats.longest_streak, unit: 'days', label: 'Longest streak' }, { icon: Mic, value: stats.total_sessions, unit: '', label: `${stats.total_attempts} total attempts` }, { icon: Clock3, value: Math.round(stats.total_speaking_seconds / 60), unit: 'min', label: 'Time spent speaking' }].map(({ icon: Icon, value, unit, label }) => <div className="stat-card" key={label}><Icon /><strong>{value} <small>{unit}</small></strong><span>{label === `${stats.total_attempts} total attempts` ? `${stats.total_sessions} sessions · ${label}` : label}</span></div>)}</div><section className="panel"><div className="panel-heading"><h2>Practice Activity</h2><span>{stats.practice_days} practice days · past year below</span></div><ActivityGrid activity={activity} today={localDate(new Date(), preferences!.timezone)} /></section><div className="progress-lower"><section className="panel"><div className="panel-heading"><h2>A clearer picture of progress</h2><span>Last {trend.length} attempts</span></div><ProgressChart values={trend} /><p className="trend-summary">{delta === null ? 'Your first score is a starting point. Another practice will begin your trend.' : `${delta > 0 ? '+' : ''}${delta.toFixed(1)} points from the first to latest attempt shown. Different topics and difficulty can affect scores.`}</p></section><section className="panel"><div className="panel-heading"><h2>Your averages</h2><span>All practice · /10</span></div>{(['grammar', 'vocabulary', 'clarity', 'overall'] as const).map(key => { const score = stats[`average_${key}_score`]; return <div key={key}><div className="average-row"><span className="capitalize">{key}</span><strong>{score === null ? '—' : Number(score).toFixed(1)} <small>/10</small></strong></div><div className="average-bar"><span style={{ width: `${(score ?? 0) * 10}%` }} /></div></div>; })}</section></div></>}</>;
}
