import { useState } from 'react';
import type { DailyActivity } from '../types';
import { dateOffset, readableDate } from '../lib/dates';
export function ActivityGrid({ activity, today }: { activity: DailyActivity[]; today: string }) {
  const [selected, setSelected] = useState(today); const lookup = new Map(activity.map(row => [row.activity_date, row]));
  const todayIndex = new Date(`${today}T12:00:00Z`).getUTCDay(); const last = dateOffset(today, 6 - todayIndex); const first = dateOffset(last, -370);
  const selectedDay = lookup.get(selected);
  return <><div className="activity-scroll"><div className="activity-grid" aria-label="Practice activity, one square per calendar day">{Array.from({ length: 371 }, (_, index) => { const day = dateOffset(first, index); const value = lookup.get(day); const count = value?.session_count ?? 0; const future = day > today; const label = `${readableDate(day)}: ${count} ${count === 1 ? 'session' : 'sessions'}, ${Math.round((value?.speaking_seconds ?? 0) / 60)} minutes practiced`; return <button key={day} type="button" className={`activity-cell level-${Math.min(count, 3)} ${future ? 'future' : ''}`} title={label} aria-label={label} aria-pressed={selected === day} disabled={future} onClick={() => setSelected(day)} onFocus={() => setSelected(day)} onMouseEnter={() => setSelected(day)} />; })}</div></div><div className="activity-meta"><span>Every square is a practice day.</span><div className="activity-legend"><span>Less</span>{[0, 1, 2, 3].map(n => <span key={n} className={`activity-cell level-${n}`} aria-hidden="true" />)}<span>More</span></div></div><div className="activity-day" aria-live="polite">{readableDate(selected)} · {selectedDay?.session_count ?? 0} sessions · {selectedDay?.attempt_count ?? 0} attempts · {Math.round((selectedDay?.speaking_seconds ?? 0) / 60)} minutes practiced</div></>;
}
export function ProgressChart({ values }: { values: { overall_score: number; completed_at: string }[] }) {
  const width = 550; const height = 200; const pad = 28; const bottom = height - pad;
  const points = values.map((row, i) => ({ x: values.length === 1 ? width / 2 : pad + i / (values.length - 1) * (width - 2 * pad), y: bottom - row.overall_score / 10 * (height - 2 * pad) }));
  return <><svg viewBox={`0 0 ${width} ${height}`} className="score-chart" role="img" aria-label={`Recent overall scores out of 10: ${values.map(v => v.overall_score.toFixed(1)).join(', ')}`}><defs><linearGradient id="chartGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#409fff" stopOpacity=".17" /><stop offset="100%" stopColor="#409fff" stopOpacity="0" /></linearGradient></defs>{[0, 5, 10].map(value => { const y = bottom - value / 10 * (height - 2 * pad); return <g key={value}><line x1={pad} x2={width - pad} y1={y} y2={y} className="chart-grid" /><text x="4" y={y + 4} className="chart-label">{value}</text></g>; })}{points.length > 1 && <><path d={`M ${points[0].x} ${bottom} L ${points.map(p => `${p.x} ${p.y}`).join(' L ')} L ${points.at(-1)!.x} ${bottom} Z`} className="chart-area" /><polyline points={points.map(p => `${p.x},${p.y}`).join(' ')} className="chart-line" /></>}{points.map((point, i) => <circle key={i} cx={point.x} cy={point.y} r="4" className="chart-dot"><title>{readableDate(values[i].completed_at)}: {values[i].overall_score.toFixed(1)}/10</title></circle>)}</svg><details className="chart-data"><summary className="text-button">View scores as a list</summary><ol>{values.map((row, i) => <li key={i}>{readableDate(row.completed_at)} — {row.overall_score.toFixed(1)} / 10</li>)}</ol></details></>;
}
